/// Provider dimension (slowly changing, Type 2). One row per provider version with specialty, department, NPI, facility, contract type, and years of experience. Filter is_current = 1 to count each provider once on the active record.
table dim_provider
	lineageTag: ec130066-7f36-404c-8375-37621c6bdec1
	sourceLineageTag: [dbo].[dim_provider]

	column provider_id
		dataType: string
		lineageTag: 073a1b3a-e1c0-4c35-96bd-59ef27a06017
		sourceLineageTag: provider_id
		summarizeBy: none
		sourceColumn: provider_id

		annotation SummarizationSetBy = Automatic

	column first_name
		dataType: string
		lineageTag: 7bd2a88d-db69-4d5e-8856-8736292ba265
		sourceLineageTag: first_name
		summarizeBy: none
		sourceColumn: first_name

		annotation SummarizationSetBy = Automatic

	column last_name
		dataType: string
		lineageTag: c884cecd-3fc0-48fd-9ea4-08fb93c27172
		sourceLineageTag: last_name
		summarizeBy: none
		sourceColumn: last_name

		annotation SummarizationSetBy = Automatic

	column display_name
		dataType: string
		lineageTag: f2d08235-b4c1-4ae4-8887-e665e963fe6a
		sourceLineageTag: display_name
		summarizeBy: none
		sourceColumn: display_name

		annotation SummarizationSetBy = Automatic

	column npi_number
		dataType: string
		lineageTag: b7ed60d0-c1c7-40b9-a58f-f7d65b6a85bd
		sourceLineageTag: npi_number
		summarizeBy: none
		sourceColumn: npi_number

		annotation SummarizationSetBy = Automatic

	column specialty
		dataType: string
		lineageTag: 6fd9f220-4447-46ff-8869-3234a258ae85
		sourceLineageTag: specialty
		summarizeBy: none
		sourceColumn: specialty

		annotation SummarizationSetBy = Automatic

	column department
		dataType: string
		lineageTag: 20f1a5d2-d440-4ee8-9531-3ed8e1012d37
		sourceLineageTag: department
		summarizeBy: none
		sourceColumn: department

		annotation SummarizationSetBy = Automatic

	column facility_id
		dataType: string
		lineageTag: e0f6aa00-d8b0-40df-b1a7-f19f2a74bd3e
		sourceLineageTag: facility_id
		summarizeBy: none
		sourceColumn: facility_id

		annotation SummarizationSetBy = Automatic

	column is_active
		dataType: int64
		formatString: 0
		lineageTag: e3ca03fa-6494-48b4-90e2-090f45c6f532
		sourceLineageTag: is_active
		summarizeBy: sum
		sourceColumn: is_active

		annotation SummarizationSetBy = Automatic

	column provider_key
		dataType: int64
		formatString: 0
		lineageTag: 9c5c10ba-9f02-4fc9-a2b9-0526e0548376
		sourceLineageTag: provider_key
		summarizeBy: none
		sourceColumn: provider_key

		annotation SummarizationSetBy = Automatic

	/// 1 = current/active provider record. Filter is_current = 1 to avoid double-counting historical versions.
	column is_current
		dataType: int64
		formatString: 0
		lineageTag: 8e3a5ba2-4ebb-4095-93c0-f4f13e72ba96
		sourceLineageTag: is_current
		summarizeBy: sum
		sourceColumn: is_current

		annotation SummarizationSetBy = Automatic

	column effective_start_date
		dataType: dateTime
		formatString: General Date
		lineageTag: fad9f6c1-9ca3-4330-932c-092a87fe5d70
		sourceLineageTag: effective_start_date
		summarizeBy: none
		sourceColumn: effective_start_date

		annotation SummarizationSetBy = Automatic

	column effective_end_date
		dataType: dateTime
		formatString: General Date
		lineageTag: df62e2c6-aa56-4bd9-944d-e5738a53196c
		sourceLineageTag: effective_end_date
		summarizeBy: none
		sourceColumn: effective_end_date

		annotation SummarizationSetBy = Automatic

	column _load_timestamp
		dataType: dateTime
		formatString: General Date
		lineageTag: 6d3fa2c4-a1cf-4621-bb54-431c596587a4
		sourceLineageTag: _load_timestamp
		summarizeBy: none
		sourceColumn: _load_timestamp

		annotation SummarizationSetBy = Automatic

	column contract_type
		dataType: string
		lineageTag: a1b2c3d4-1001-4001-a001-000000000001
		sourceLineageTag: contract_type
		summarizeBy: none
		sourceColumn: contract_type

		annotation SummarizationSetBy = Automatic

	column fte_status
		dataType: string
		lineageTag: a1b2c3d4-1001-4001-a001-000000000002
		sourceLineageTag: fte_status
		summarizeBy: none
		sourceColumn: fte_status

		annotation SummarizationSetBy = Automatic

	column years_experience
		dataType: int64
		formatString: 0
		lineageTag: a1b2c3d4-1001-4001-a001-000000000003
		sourceLineageTag: years_experience
		summarizeBy: none
		sourceColumn: years_experience

		annotation SummarizationSetBy = Automatic

	column board_certified
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a1b2c3d4-1001-4001-a001-000000000004
		sourceLineageTag: board_certified
		summarizeBy: none
		sourceColumn: board_certified

		annotation SummarizationSetBy = Automatic

	column patient_panel_size
		dataType: int64
		formatString: #,##0
		lineageTag: a1b2c3d4-1001-4001-a001-000000000005
		sourceLineageTag: patient_panel_size
		summarizeBy: none
		sourceColumn: patient_panel_size

		annotation SummarizationSetBy = Automatic

	column annual_rvu_target
		dataType: int64
		formatString: #,##0
		lineageTag: a1b2c3d4-1001-4001-a001-000000000006
		sourceLineageTag: annual_rvu_target
		summarizeBy: none
		sourceColumn: annual_rvu_target

		annotation SummarizationSetBy = Automatic

	column actual_rvu
		dataType: int64
		formatString: #,##0
		lineageTag: a1b2c3d4-1001-4001-a001-000000000011
		sourceLineageTag: actual_rvu
		summarizeBy: none
		sourceColumn: actual_rvu

		annotation SummarizationSetBy = Automatic

	column patient_satisfaction_score
		dataType: double
		formatString: 0.0
		lineageTag: a1b2c3d4-1001-4001-a001-000000000007
		sourceLineageTag: patient_satisfaction_score
		summarizeBy: none
		sourceColumn: patient_satisfaction_score

		annotation SummarizationSetBy = Automatic

	column telehealth_enabled
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a1b2c3d4-1001-4001-a001-000000000008
		sourceLineageTag: telehealth_enabled
		summarizeBy: none
		sourceColumn: telehealth_enabled

		annotation SummarizationSetBy = Automatic

	column documentation_score
		dataType: int64
		formatString: 0
		lineageTag: a1b2c3d4-1001-4001-a001-000000000009
		sourceLineageTag: documentation_score
		summarizeBy: none
		sourceColumn: documentation_score

		annotation SummarizationSetBy = Automatic

	column ehr_adoption_score
		dataType: int64
		formatString: 0
		lineageTag: a1b2c3d4-1001-4001-a001-000000000010
		sourceLineageTag: ehr_adoption_score
		summarizeBy: none
		sourceColumn: ehr_adoption_score

		annotation SummarizationSetBy = Automatic

	measure 'Avg Satisfaction Score' = AVERAGE(dim_provider[patient_satisfaction_score])
		formatString: 0.0
		lineageTag: a1b2c3d4-2001-4001-a001-000000000001

	measure 'Avg Documentation Score' = AVERAGE(dim_provider[documentation_score])
		formatString: 0
		lineageTag: a1b2c3d4-2001-4001-a001-000000000002

	measure 'Avg EHR Adoption Score' = AVERAGE(dim_provider[ehr_adoption_score])
		formatString: 0
		lineageTag: a1b2c3d4-2001-4001-a001-000000000003

	measure 'Telehealth Enabled Rate' = DIVIDE(COUNTROWS(FILTER(dim_provider, dim_provider[telehealth_enabled] = TRUE())), COUNTROWS(dim_provider))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a1b2c3d4-2001-4001-a001-000000000004

	measure 'Board Certified Rate' = DIVIDE(COUNTROWS(FILTER(dim_provider, dim_provider[board_certified] = TRUE())), COUNTROWS(dim_provider))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a1b2c3d4-2001-4001-a001-000000000005

	measure 'Avg Panel Size' = AVERAGE(dim_provider[patient_panel_size])
		formatString: #,##0
		lineageTag: a1b2c3d4-2001-4001-a001-000000000006

	measure 'Avg RVU Target' = AVERAGE(dim_provider[annual_rvu_target])
		formatString: #,##0
		lineageTag: a1b2c3d4-2001-4001-a001-000000000007

	measure 'Value-Based Provider Rate' = DIVIDE(COUNTROWS(FILTER(dim_provider, dim_provider[contract_type] = "Value-Based")), COUNTROWS(dim_provider))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a1b2c3d4-2001-4001-a001-000000000008

	measure 'Avg Actual RVU' = AVERAGE(dim_provider[actual_rvu])
		formatString: #,##0
		lineageTag: a1b2c3d4-2001-4001-a001-000000000009

	measure 'RVU Attainment %' = DIVIDE(SUM(dim_provider[actual_rvu]), SUM(dim_provider[annual_rvu_target]))
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a1b2c3d4-2001-4001-a001-000000000010

	measure 'Actual Panel Count' =
			VAR _current_provider = SELECTEDVALUE(dim_provider[provider_key])
			RETURN IF(ISBLANK(_current_provider), DIVIDE(DISTINCTCOUNT(fact_encounter[patient_key]), DISTINCTCOUNT(dim_provider[provider_key])), CALCULATE(DISTINCTCOUNT(fact_encounter[patient_key])))
		formatString: #,##0
		lineageTag: a1b2c3d4-2001-4001-a001-000000000011

	measure 'Panel Utilization %' = DIVIDE([Actual Panel Count], [Avg Panel Size])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a1b2c3d4-2001-4001-a001-000000000012

	partition dim_provider = entity
		mode: directLake
		source
			entityName: dim_provider
			expressionSource: 'DirectLake - lh_gold_curated'

